name: pull_request
on: [pull_request]
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running lint for ${{ github.ref }} branch"

      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Running Lint
        run: uv run --with ruff ruff check .

  run_tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests for ${{ github.ref }} branch"

      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Running tests
        run: uv run --with pytest --with pytest-cov pytest --cov-report=term --cov .

  mypy:
    name: "Mypy Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Running Mypy
        run: uv run --with mypy python3 -m mypy . --follow-untyped-imports --explicit-package-bases --check-untyped-defs
